const candidates = [
  {
    firstName: "María",
    lastName: "González",
    profession: "Desarrolladora Frontend",
    country: "Argentina",
    skills: ["JavaScript", "React", "CSS", "HTML", "TypeScript"],
  },
  {
    firstName: "Carlos",
    lastName: "Ramírez",
    profession: "Analista de Datos",
    country: "México",
    skills: ["Python", "SQL", "Power BI", "Excel", "Machine Learning"],
  },
  {
    firstName: "Lucía",
    lastName: "Martínez",
    profession: "Diseñadora UX/UI",
    country: "España",
    skills: ["Figma", "Adobe XD", "Prototipado", "Investigación de Usuarios"],
  },
  {
    firstName: "Javier",
    lastName: "Fernández",
    profession: "Ingeniero de Software",
    country: "Chile",
    skills: ["Java", "Spring Boot", "Microservicios", "Docker", "Kubernetes"],
  },
  {
    firstName: "Sofía",
    lastName: "Pérez",
    profession: "Project Manager",
    country: "Colombia",
    skills: ["Scrum", "Kanban", "Gestión de Equipos", "Jira", "Comunicación"],
  },
  {
    firstName: "Diego",
    lastName: "López",
    profession: "Administrador de Sistemas",
    country: "Uruguay",
    skills: ["Linux", "Windows Server", "Redes", "AWS", "Bash"],
  },
  {
    firstName: "Valentina",
    lastName: "Morales",
    profession: "Especialista en Marketing Digital",
    country: "Perú",
    skills: [
      "SEO",
      "Google Ads",
      "Facebook Ads",
      "Email Marketing",
      "Analytics",
    ],
  },
  {
    firstName: "Andrés",
    lastName: "Castro",
    profession: "Arquitecto de Software",
    country: "Ecuador",
    skills: [
      "Arquitectura en la Nube",
      "AWS",
      "Azure",
      "Diseño de APIs",
      "DevOps",
    ],
  },
];

const candidates2 = [
  {
    firstName: "Tomás",
    lastName: "Navarro",
    profession: "Tester QA",
    country: "México",
    skills: [
      "Redes",
      "TypeScript",
      "Investigación de Usuarios",
      "Google Ads",
      "SQL",
      "Prototipado",
    ],
  },
  {
    firstName: "Natalia",
    lastName: "Morales",
    profession: "Project Manager",
    country: "Uruguay",
    skills: ["Excel", "Big Data", "Terraform", "Laravel", "NoSQL", "Vue"],
  },
  {
    firstName: "Andrés",
    lastName: "Mendoza",
    profession: "Consultor de Negocios",
    country: "Paraguay",
    skills: ["Facebook Ads", "HTML", "React", "Docker", "Python", "MongoDB"],
  },
  {
    firstName: "Juan",
    lastName: "Fernández",
    profession: "Ingeniero de Software",
    country: "Ecuador",
    skills: [
      "Analytics",
      "Docker",
      "Deep Learning",
      "Gestión de Equipos",
      "Power BI",
    ],
  },
  {
    firstName: "Ricardo",
    lastName: "Chávez",
    profession: "Ingeniero de Software",
    country: "Paraguay",
    skills: [
      "HTML",
      "C#",
      "NoSQL",
      "Investigación de Usuarios",
      "Deep Learning",
      "PHP",
    ],
  },
  {
    firstName: "Camila",
    lastName: "Mendoza",
    profession: "Desarrolladora Frontend",
    country: "España",
    skills: ["React", "TypeScript", "CSS", "Docker", "MongoDB"],
  },
  {
    firstName: "Fernando",
    lastName: "Jiménez",
    profession: "Administrador de Sistemas",
    country: "Argentina",
    skills: ["Linux", "Redes", "Docker", "AWS", "Jenkins", "Terraform"],
  },
  {
    firstName: "Paula",
    lastName: "Vargas",
    profession: "Diseñadora UX/UI",
    country: "México",
    skills: [
      "Figma",
      "Prototipado",
      "Investigación de Usuarios",
      "Adobe XD",
      "HTML",
    ],
  },
  {
    firstName: "Luis",
    lastName: "Ortega",
    profession: "Analista de Datos",
    country: "Chile",
    skills: ["SQL", "Python", "Excel", "Machine Learning", "Big Data"],
  },
  {
    firstName: "Gabriela",
    lastName: "Castro",
    profession: "Especialista en Marketing Digital",
    country: "Colombia",
    skills: [
      "SEO",
      "Google Ads",
      "Facebook Ads",
      "Analytics",
      "Email Marketing",
    ],
  },
  {
    firstName: "Miguel",
    lastName: "Reyes",
    profession: "Product Owner",
    country: "Uruguay",
    skills: ["Scrum", "Kanban", "Gestión de Equipos", "Jira", "Confluence"],
  },
  {
    firstName: "Esteban",
    lastName: "Torres",
    profession: "Científica de Datos",
    country: "Perú",
    skills: ["Python", "Deep Learning", "Machine Learning", "Power BI", "SQL"],
  },
  {
    firstName: "Carolina",
    lastName: "Ibarra",
    profession: "Desarrolladora Frontend",
    country: "España",
    skills: ["Vue", "JavaScript", "CSS", "TypeScript", "HTML"],
  },
  {
    firstName: "Hernán",
    lastName: "Ríos",
    profession: "Ingeniero DevOps",
    country: "Bolivia",
    skills: ["AWS", "Docker", "Kubernetes", "Jenkins", "Terraform"],
  },
  {
    firstName: "Isabel",
    lastName: "Navarro",
    profession: "Tester QA",
    country: "Paraguay",
    skills: ["Scrum", "Jira", "Automatización", "Selenium", "SQL"],
  },
  {
    firstName: "Alejandra",
    lastName: "Paredes",
    profession: "Project Manager",
    country: "México",
    skills: ["Gestión de Equipos", "Kanban", "Jira", "Scrum", "Comunicación"],
  },
  {
    firstName: "Roberto",
    lastName: "Medina",
    profession: "Desarrollador Backend",
    country: "Argentina",
    skills: ["Java", "Spring Boot", "SQL", "Microservicios", "Docker"],
  },
  {
    firstName: "Valentina",
    lastName: "González",
    profession: "Diseñadora UX/UI",
    country: "Chile",
    skills: [
      "Figma",
      "Adobe XD",
      "Investigación de Usuarios",
      "Prototipado",
      "UI Design",
    ],
  },
  {
    firstName: "Patricia",
    lastName: "Aguilar",
    profession: "Consultor de Negocios",
    country: "Colombia",
    skills: [
      "Excel",
      "Análisis de Procesos",
      "Comunicación",
      "Power BI",
      "SQL",
    ],
  },
  {
    firstName: "Martín",
    lastName: "Silva",
    profession: "Administrador de Sistemas",
    country: "Ecuador",
    skills: ["Linux", "Windows Server", "AWS", "Redes", "Docker"],
  },
];
